services:
  postgres:
    image: postgres:15-alpine
    container_name: saas_postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 7PmWaW010vYKAl
      POSTGRES_DB: saas_analytics
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - distributed_network

  redis:
    image: redis:7-alpine
    container_name: saas_redis_queue
    ports:
      - "6379:6379"
    networks:
      - distributed_network

volumes:
  pgdata:

networks:
  distributed_network:
    driver: bridge