services:
  postgres:
    image: postgres:15-alpine
    container_name: saas_postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 7PmWaW010vYKAl
      POSTGRES_DB: saas_analytics
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - distributed_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d saas_analytics"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  redis:
    image: redis:7-alpine
    container_name: saas_redis_queue
    ports:
      - "6379:6379"
    networks:
      - distributed_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:

networks:
  distributed_network:
    driver: bridge